//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Required {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Required() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Movies.Required", typeof(Required).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor Full Name is Required !!! .
        /// </summary>
        public static string Actname {
            get {
                return ResourceManager.GetString("Actname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Description is required !!!.
        /// </summary>
        public static string desc {
            get {
                return ResourceManager.GetString("desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Poster is required !!!.
        /// </summary>
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Video is required.
        /// </summary>
        public static string file2 {
            get {
                return ResourceManager.GetString("file2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Country is required !!!.
        /// </summary>
        public static string moviecountry {
            get {
                return ResourceManager.GetString("moviecountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Duration is required !!!.
        /// </summary>
        public static string movieduration {
            get {
                return ResourceManager.GetString("movieduration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Language is required !!!.
        /// </summary>
        public static string movielanguage {
            get {
                return ResourceManager.GetString("movielanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Name is requried  !!!.
        /// </summary>
        public static string moviename {
            get {
                return ResourceManager.GetString("moviename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster of Movie is required !!!.
        /// </summary>
        public static string movieposter {
            get {
                return ResourceManager.GetString("movieposter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Production is required !!!.
        /// </summary>
        public static string movieprodate {
            get {
                return ResourceManager.GetString("movieprodate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Movie is required !!!.
        /// </summary>
        public static string movietype {
            get {
                return ResourceManager.GetString("movietype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Video of Movie is required !!!.
        /// </summary>
        public static string movievideo {
            get {
                return ResourceManager.GetString("movievideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name is Requierd !!!.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name is required !!!.
        /// </summary>
        public static string typemov {
            get {
                return ResourceManager.GetString("typemov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email is Required !!!.
        /// </summary>
        public static string useremail {
            get {
                return ResourceManager.GetString("useremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture is required !!!.
        /// </summary>
        public static string userimg {
            get {
                return ResourceManager.GetString("userimg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is required !!!.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Password is Required !!!.
        /// </summary>
        public static string userpass {
            get {
                return ResourceManager.GetString("userpass", resourceCulture);
            }
        }
    }
}
