//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Movies.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor Picture.
        /// </summary>
        public static string ImgActor {
            get {
                return ResourceManager.GetString("ImgActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Country.
        /// </summary>
        public static string moviecountry {
            get {
                return ResourceManager.GetString("moviecountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Description.
        /// </summary>
        public static string moviedescription {
            get {
                return ResourceManager.GetString("moviedescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Duration.
        /// </summary>
        public static string movieduration {
            get {
                return ResourceManager.GetString("movieduration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Language.
        /// </summary>
        public static string movielanguage {
            get {
                return ResourceManager.GetString("movielanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Name.
        /// </summary>
        public static string moviename {
            get {
                return ResourceManager.GetString("moviename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Poster.
        /// </summary>
        public static string movieposter {
            get {
                return ResourceManager.GetString("movieposter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Date.
        /// </summary>
        public static string movieproductiondate {
            get {
                return ResourceManager.GetString("movieproductiondate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Type.
        /// </summary>
        public static string movietype {
            get {
                return ResourceManager.GetString("movietype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Date.
        /// </summary>
        public static string movieuploaddate {
            get {
                return ResourceManager.GetString("movieuploaddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Video.
        /// </summary>
        public static string movievideo {
            get {
                return ResourceManager.GetString("movievideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture.
        /// </summary>
        public static string profilepic {
            get {
                return ResourceManager.GetString("profilepic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher Name.
        /// </summary>
        public static string publishername {
            get {
                return ResourceManager.GetString("publishername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        public static string typename {
            get {
                return ResourceManager.GetString("typename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
